[profile.default]
src = "src"
out = "out"
libs = ["lib"]
rpc_endpoints = { sepolia-eth = "https://1rpc.io/sepolia", arb-sepolia = "https://arbitrum-sepolia-rpc.publicnode.com"}
remappings = ["openzeppelin/contracts=lib/openzeppelin-contracts/contracts", '@ccip=lib/ccip/', "@chainlink/local/=lib/chainlink-local/"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
